import { Patient } from "../types/types";

export const patients: Patient[] = [
  {
    id: 'P001',
    name: 'John Doe',
    age: 45,
    gender: 'Male',
    address: '123 Street',
    consultations: [
      {
        date: '2024-05-10',
        doctor: 'Dr. Smith',
        symptoms: 'Cough and fever',
        duration: '3 days',
        severity: 6,
        triggers: 'Cold weather',
        relievingFactors: 'Warm liquids',
        chronicConditions: ['Hypertension'],
        surgeries: 'Appendectomy',
        familyHistory: 'Father had diabetes',
        takingMedication: 'Yes',
        medicationsList: 'Paracetamol',
        supplements: 'Vitamin C',
        allergies: 'None',
        sleep: 'Normal',
        appetite: 'Good',
        waterIntake: '2L',
        bowel: 'normal',
        activity: 'moderate',
        height: '170',
        weight: '70',
        bp: '130/80',
        pulse: '72',
        temperature: '98.6',
        spo2: '98%',
        diagnosis: 'Viral infection',
        investigations: ['Hemogram', 'ESR'],
        otherTests: 'X-ray Chest',
      },
      {
        date: '2024-06-15',
        doctor: 'Dr. Allen',
        symptoms: 'Headache',
        duration: '2 days',
        severity: 4,
        triggers: 'Stress',
        relievingFactors: 'Sleep',
        chronicConditions: ['Hypertension'],
        surgeries: '',
        familyHistory: 'None',
        takingMedication: 'No',
        medicationsList: '',
        supplements: '',
        allergies: 'None',
        sleep: 'Disturbed',
        appetite: 'Reduced',
        waterIntake: '1L',
        bowel: 'normal',
        activity: 'sedentary',
        height: '170',
        weight: '68',
        bp: '125/85',
        pulse: '76',
        temperature: '98.4',
        spo2: '97%',
        diagnosis: 'Migraine',
        investigations: ['MRI'],
        otherTests: '',
      },
    ],
  },
  {
    id: 'P002',
    name: 'Jane Smith',
    age: 32,
    gender: 'Female',
    address: '456 Avenue',
    consultations: [
      {
        date: '2024-07-01',
        doctor: 'Dr. Lee',
        symptoms: 'Abdominal pain',
        duration: '1 week',
        severity: 7,
        triggers: 'Spicy food',
        relievingFactors: 'Antacids',
        chronicConditions: ['IBS'],
        surgeries: '',
        familyHistory: 'Mother has ulcers',
        takingMedication: 'Yes',
        medicationsList: 'Omeprazole',
        supplements: 'Probiotics',
        allergies: 'Peanuts',
        sleep: 'Disturbed',
        appetite: 'Poor',
        waterIntake: '1.5L',
        bowel: 'irregular',
        activity: 'low',
        height: '165',
        weight: '60',
        bp: '120/75',
        pulse: '80',
        temperature: '98.7',
        spo2: '99%',
        diagnosis: 'Gastritis',
        investigations: ['Ultrasound'],
        otherTests: 'Stool test',
      },
    ],
  },
  {
    id: 'P003',
    name: 'Amit Patel',
    age: 60,
    gender: 'Male',
    address: '789 Lane',
    consultations: [
      {
        date: '2024-03-22',
        doctor: 'Dr. Reddy',
        symptoms: 'Shortness of breath',
        duration: '2 weeks',
        severity: 8,
        triggers: 'Exertion',
        relievingFactors: 'Rest',
        chronicConditions: ['COPD'],
        surgeries: 'Hernia repair',
        familyHistory: 'Brother has asthma',
        takingMedication: 'Yes',
        medicationsList: 'Inhaler',
        supplements: '',
        allergies: 'Dust',
        sleep: 'Poor',
        appetite: 'Moderate',
        waterIntake: '2L',
        bowel: 'normal',
        activity: 'light',
        height: '175',
        weight: '75',
        bp: '135/85',
        pulse: '90',
        temperature: '98.2',
        spo2: '94%',
        diagnosis: 'Bronchitis',
        investigations: ['Chest X-ray', 'PFT'],
        otherTests: '',
      },
    ],
  },
  {
    id: 'P004',
    name: 'Meena Rani',
    age: 28,
    gender: 'Female',
    address: '321 Boulevard',
    consultations: [
      {
        date: '2024-04-18',
        doctor: 'Dr. Gupta',
        symptoms: 'Joint pain',
        duration: '1 month',
        severity: 5,
        triggers: 'Weather change',
        relievingFactors: 'Heat therapy',
        chronicConditions: [],
        surgeries: '',
        familyHistory: 'Grandmother had arthritis',
        takingMedication: 'No',
        medicationsList: '',
        supplements: 'Calcium',
        allergies: 'None',
        sleep: 'Good',
        appetite: 'Normal',
        waterIntake: '2L',
        bowel: 'regular',
        activity: 'moderate',
        height: '160',
        weight: '55',
        bp: '115/70',
        pulse: '70',
        temperature: '98.5',
        spo2: '99%',
        diagnosis: 'Early arthritis',
        investigations: ['RA Factor', 'CRP'],
        otherTests: '',
      },
    ],
  },
];